// <auto-generated />
using BANCO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BANCO.Data.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BANCO.Core.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CpfCliente")
                        .HasColumnName("CPF_CLIENTE")
                        .HasColumnType("varchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("NomeBanco")
                        .HasColumnName("NOME_BANCO")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("NomeCliente")
                        .HasColumnName("NOME_CLIENTE")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.Property<int>("Numero")
                        .HasColumnName("NUMERO")
                        .HasColumnType("int");

                    b.Property<decimal>("RendaMensal")
                        .HasColumnName("RENDA_MENSAL_CLIENTE")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Saldo")
                        .HasColumnName("SALDO")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK_TB_CONTA");

                    b.ToTable("TB_CONTAS","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
